"""add identity keys to users

Revision ID: 8662fc698943
Revises: e32ea88cfd28
Create Date: 2026-05-20 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '8662fc698943'
down_revision: Union[str, None] = 'e32ea88cfd28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('identity_key', sa.String(length=512), nullable=True))
    op.add_column('users', sa.Column('ed25519_public_key', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ed25519_public_key')
    op.drop_column('users', 'identity_key')
    # ### end Alembic commands ###
